-- Active: 1668065856987@@127.0.0.1@3306
DROP SCHEMA IF EXISTS `project`;

CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8;
USE `project`;

CREATE TABLE user
(USER_ID   INT AUTO_INCREMENT,
FIRST_NAME  VARCHAR(20),
LAST_NAME   VARCHAR(20),
PHONE_NUMBER VARCHAR(20),
-- COUNTRY_NAME VARCHAR(10),
COUNTRY_NAME VARCHAR(50),
PROVINCE   VARCHAR(25),
-- ROLE  VARCHAR(10),
ROLE  VARCHAR(30),
PACKAGE_DONE INT,
STREET_ADDRESS VARCHAR(40),
PASSWORD VARCHAR(40),
PRIMARY KEY(USER_ID));

CREATE TABLE package
(USER_ID   INT,
PACKAGE_ID  INT AUTO_INCREMENT,
BUDGET  DEC(10,2),
-- BUDGET  DEC(6,2),
CREATE_TIME DATETIME,
DEADLINE  DATETIME,
PRIMARY KEY(PACKAGE_ID),
FOREIGN KEY(USER_ID) REFERENCES user(USER_ID));

CREATE TABLE state
(PACKAGE_ID  INT,
START_TIME DATETIME,
END_TIME DATETIME,
STATE_NAME VARCHAR(20),
FOREIGN KEY(PACKAGE_ID) REFERENCES package(PACKAGE_ID));

CREATE TABLE machine_type
(MACHINE_NAME VARCHAR(50),
MACHINE_VERSION VARCHAR(20),
PRICE FLOAT,
PRIMARY KEY(MACHINE_NAME,MACHINE_VERSION));

CREATE TABLE plant
(PLANT_ID  INT AUTO_INCREMENT,
PLANT_NAME VARCHAR(20),
PHONE_NUMBER VARCHAR(20),
BOSS_ID  INT,
COUNTRY_NAME VARCHAR(10),
PROVINCE  VARCHAR(25),
STREET_ADDRESS  VARCHAR(40),
PRIMARY KEY(PLANT_ID));

CREATE TABLE machine
(MACHINE_NAME VARCHAR(50),
MACHINE_VERSION VARCHAR(20),
PRICE FLOAT,
PLANT_ID  INT,
MACHINE_ID  INT AUTO_INCREMENT,
PLANT_LABEL  VARCHAR(20),
STATE VARCHAR(20),
PRIMARY KEY(MACHINE_ID),
FOREIGN KEY(MACHINE_NAME,MACHINE_VERSION) REFERENCES machine_type(MACHINE_NAME,MACHINE_VERSION),
FOREIGN KEY(PLANT_ID) REFERENCES plant(PLANT_ID));

CREATE TABLE chip_type
(CHIP_NAME  VARCHAR(20),
CHIP_VERSION  VARCHAR(20),
PRICE FLOAT,
PRIMARY KEY(CHIP_NAME,CHIP_VERSION));

CREATE TABLE chip
(CHIP_NAME  VARCHAR(20),
CHIP_VERSION  VARCHAR(20),
PRICE  INT,
PACKAGE_ID  INT,
CHIP_ID  INT AUTO_INCREMENT,
PLANT_ID INT,
PRIMARY KEY(CHIP_ID),
FOREIGN KEY(CHIP_NAME,CHIP_VERSION) REFERENCES chip_type(CHIP_NAME,CHIP_VERSION),
FOREIGN KEY(PACKAGE_ID) REFERENCES package(PACKAGE_ID),
FOREIGN KEY(PLANT_ID) REFERENCES plant(PLANT_ID));

CREATE TABLE operation_type
(OPERATION_NAME  VARCHAR(20),
PRIMARY KEY(OPERATION_NAME));

CREATE TABLE operation
(OPERATION_NAME  VARCHAR(20),
OPERATION_ID  INT AUTO_INCREMENT,
START_TIME  DATETIME,
END_TIME  DATETIME,
PRIMARY KEY(OPERATION_ID),
FOREIGN KEY(OPERATION_NAME) REFERENCES operation_type(OPERATION_NAME));

CREATE TABLE operation_with_machine
(OPERATION_ID  INT,
MACHINE_ID INT,
START_TIME  DATETIME,
END_TIME  DATETIME,
PRIMARY KEY(OPERATION_ID,MACHINE_ID),
FOREIGN KEY(OPERATION_ID) REFERENCES operation(OPERATION_ID),
FOREIGN KEY(MACHINE_ID) REFERENCES machine(MACHINE_ID));

CREATE TABLE operation_with_chip
(OPERATION_ID INT,
CHIP_ID INT,
FOREIGN KEY(OPERATION_ID) REFERENCES operation(OPERATION_ID),
FOREIGN KEY(CHIP_ID) REFERENCES chip(CHIP_ID)
);

CREATE TABLE plant_with_package
(PACKAGE_ID  INT,
PLANT_ID  INT,
PRIMARY KEY(PACKAGE_ID,PLANT_ID),
FOREIGN KEY(PACKAGE_ID) REFERENCES package(PACKAGE_ID),
FOREIGN KEY(PLANT_ID) REFERENCES plant(PLANT_ID));

CREATE TABLE chip_type_with_operation_type
(ORDER_OP  VARCHAR(10),
OPERATION_NAME  VARCHAR(20),
CHIP_NAME  VARCHAR(20),
CHIP_VERSION  VARCHAR(20),
PRIMARY KEY(OPERATION_NAME,CHIP_NAME,CHIP_VERSION),
FOREIGN KEY(OPERATION_NAME) REFERENCES operation_type(OPERATION_NAME),
FOREIGN KEY(CHIP_NAME, CHIP_VERSION) REFERENCES chip_type(CHIP_NAME,CHIP_VERSION));

CREATE TABLE machine_type_with_operation_type
(OPERATION_NAME  VARCHAR(20),
MACHINE_NAME VARCHAR(50),
MACHINE_VERSION VARCHAR(20),
EXPENSE  INT,
DURATION  INT,
PRIMARY KEY(OPERATION_NAME,MACHINE_NAME,MACHINE_VERSION),
FOREIGN KEY(OPERATION_NAME) REFERENCES operation_type(OPERATION_NAME),
FOREIGN KEY(MACHINE_NAME,MACHINE_VERSION) REFERENCES machine_type(MACHINE_NAME,MACHINE_VERSION));
